### ISSUE TITLE
[BUG] model.PdfFunctionType0.Evaluate crashes on text extraction

### ISSUE THREAD

**Issue by Kleissner** [unidoc/unipdf#290]
## Description
Following panic happens when trying to extract text (via extractor.ExtractText) from this PDF file: 
[489a9cf7-af5f-4fa9-97ff-2b8c176e8355.pdf](https://github.com/unidoc/unipdf/files/4406923/489a9cf7-af5f-4fa9-97ff-2b8c176e8355.pdf)

```
panic: runtime error: index out of range [1024] with length 1024

goroutine 1 [running]:
github.com/unidoc/unipdf/model.(*PdfFunctionType0).Evaluate(0xc00004e1a0, 0xc000241700, 0x4, 0x4, 0x4, 0x3, 0x3, 0xc000241700, 0xc000232770)
        C:/Temp/Go/src/github.com/unidoc/unipdf/model/functions.go:345 +0x94e
github.com/unidoc/unipdf/model.(*PdfColorspaceDeviceN).ColorFromFloats(0xc000507ac0, 0xc000241700, 0x4, 0x4, 0x4, 0x4, 0x0, 0x0)
        C:/Temp/Go/src/github.com/unidoc/unipdf/model/colorspace.go:2812 +0x76
github.com/unidoc/unipdf/model.(*PdfColorspaceDeviceN).ColorFromPdfObjects(0xc000507ac0, 0xc000232740, 0x4, 0x4, 0x6a1cd7, 0xc000071790, 0x6abe4d, 0xc000071c48)
        C:/Temp/Go/src/github.com/unidoc/unipdf/model/colorspace.go:2836 +0xc5
github.com/unidoc/unipdf/contentstream.(*ContentStreamProcessor).handleCommand_scn(0xc000071c48, 0xc0002d5c50, 0xc000132090, 0x7c3c60, 0xc000507ac0)
        C:/Temp/Go/src/github.com/unidoc/unipdf/contentstream/processor.go:435 +0x7f
github.com/unidoc/unipdf/contentstream.(*ContentStreamProcessor).Process(0xc000071c48, 0xc000132090, 0x0, 0x0)
        C:/Temp/Go/src/github.com/unidoc/unipdf/contentstream/processor.go:247 +0x792
github.com/unidoc/unipdf/extractor.(*Extractor).extractPageText(0xc0002326c0, 0xc000342000, 0x2f8b, 0xc000132090, 0x0, 0x1c0108, 0x0, 0xc000342000, 0xc6c440, 0x1c0108)
        C:/Temp/Go/src/github.com/unidoc/unipdf/extractor/text.go:336 +0x60a
github.com/unidoc/unipdf/extractor.(*Extractor).ExtractPageText(0xc0002326c0, 0x40db64, 0x7276e0, 0xc0002d5b90, 0xc000071e28, 0x6ae61b)
        C:/Temp/Go/src/github.com/unidoc/unipdf/extractor/text.go:45 +0x5c
github.com/unidoc/unipdf/extractor.(*Extractor).ExtractTextWithStats(0xc0002326c0, 0xc0002326c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Temp/Go/src/github.com/unidoc/unipdf/extractor/text.go:36 +0x39
github.com/unidoc/unipdf/extractor.(*Extractor).ExtractText(...)
        C:/Temp/Go/src/github.com/unidoc/unipdf/extractor/text.go:29
main.outputPdfText(0xc00000a270, 0x28, 0x0, 0x0)
```

## Expected Behavior
The PDF file appears to be corrupted, but that shouldn't lead to a crash of the entire application. It should instead either return an error or silently return.

## Reproduce
* The PDF file was already linked above: [489a9cf7-af5f-4fa9-97ff-2b8c176e8355.pdf](https://github.com/unidoc/unipdf/files/4406923/489a9cf7-af5f-4fa9-97ff-2b8c176e8355.pdf)
* Below is simple test program that loads the file and extracts text. Don't forget to add the license.
* Run it with `PDF_Extract.exe 489a9cf7-af5f-4fa9-97ff-2b8c176e8355.pdf` and it will crash

```go
/*
 * PDF to text: Extract all text for each page of a pdf file.
 */

package main

import (
	"fmt"
	"os"

	"github.com/unidoc/unipdf/common/license"
	"github.com/unidoc/unipdf/extractor"
	pdf "github.com/unidoc/unipdf/model"
)

const unidocLicenseKey string = `[ENTER_LICENSE_HERE]`
const unidocLicenseCustomerName string = "LICENSE_NAME"

func init() {
	// load the unidoc license (v3)
	license.SetLicenseKey(unidocLicenseKey, unidocLicenseCustomerName)
}

func main() {
	if len(os.Args) < 2 {
		fmt.Printf("Usage: go run pdf_extract_text.go input.pdf\n")
		os.Exit(1)
	}

	inputPath := os.Args[1]

	err := outputPdfText(inputPath)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
}

// outputPdfText prints out contents of PDF file to stdout.
func outputPdfText(inputPath string) error {
	f, err := os.Open(inputPath)
	if err != nil {
		return err
	}

	defer f.Close()

	pdfReader, err := pdf.NewPdfReader(f)
	if err != nil {
		return err
	}

	numPages, err := pdfReader.GetNumPages()
	if err != nil {
		return err
	}

	fmt.Printf("--------------------\n")
	fmt.Printf("PDF to text extraction:\n")
	fmt.Printf("--------------------\n")
	for i := 0; i < numPages; i++ {
		pageNum := i + 1

		page, err := pdfReader.GetPage(pageNum)
		if err != nil {
			return err
		}

		ex, err := extractor.New(page)
		if err != nil {
			return err
		}

		text, err := ex.ExtractText()
		if err != nil {
			return err
		}

		fmt.Println("------------------------------")
		fmt.Printf("Page %d:\n", pageNum)
		fmt.Printf("\"%s\"\n", text)
		fmt.Println("------------------------------")
	}

	return nil
}
```

**Comment by gunnsth** [comment]
Fixed by #291.  Fix now in development branch, will be in next release.
